### ISSUE TITLE
Mail system

### ISSUE THREAD

**Issue by Niklan** [dockerizedrupal/documentation#1]
Hi.

Is there preinstalled mail system or i need it to install manualy? I trying to send email from local site, without any SMTP layer, and messages are not sends. Can you recommend what I need to install to make it work?

**Comment by Niklan** [comment]
And create repo for all issues, or something like that. Because sometimes it's not obvious where i need to create issue. F.e. current cubject can be in every PHP repo. This is common question, not strongly depended on PHP container and its version.

**Comment by MartinAnt** [comment]
Hey, Can you give more info about this ?

If you are using a docker-compose file generated with drupal-compose then it's likely that your setup contains mailcatcher container which is, as the name suggests, catching all your outgoing emails. You could check that by going to your vhost home and checking from under your running project if the mailcatcher service is runnig. If it is running then there is also a link provided there which will allow you to navigate to your mailcatcher UI and actually see the emails that the PHP sent out. 

If your mail is not appearing there or the mailcatcher is in fact not running and you are still unable to send out emails then the problem lies elsewhere.

**Comment by viljaste** [comment]
Closing this as this project is unfortunately not active anymore.
